# Generated by Django 2.2.6 on 2021-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210407_2253'),
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transactions',
            field=models.ManyToManyField(through='home.Transaction', to='home.CryptoCoins3'),
        ),
    ]
