# Generated by Django 2.2.6 on 2021-04-08 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account_app', '0001_initial'),
        ('coins_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account_app.Profile'),
        ),
        migrations.AddField(
            model_name='coinsinfo',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=False, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
