# Generated by Django 2.2.6 on 2021-04-13 11:39

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0002_passwordrsttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='no_data', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_surrname',
            field=models.CharField(default='no_data', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_info',
            field=models.CharField(default='no_data', max_length=30),
        ),
    ]
