# Generated by Django 2.2.6 on 2021-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app', '0003_auto_20210413_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_surrname',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_info',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
