# Generated by Django 2.2.6 on 2021-03-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_coin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoCoins',
        ),
    ]
