# Generated by Django 2.2.6 on 2021-04-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'permissions': (('add_article', 'Can publish articles'),)},
        ),
    ]
