# Generated by Django 2.2.6 on 2021-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210327_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture_file',
            field=models.ImageField(upload_to='images/article/'),
        ),
    ]
