# Generated by Django 2.2.6 on 2021-03-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210327_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_file',
            field=models.ImageField(upload_to='static/images/article/'),
        ),
    ]
