# Generated by Django 2.2.6 on 2021-03-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210328_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoins2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('usd_market_cap', models.FloatField()),
                ('usd_24h_vol', models.FloatField()),
            ],
        ),
    ]
