# Generated by Django 2.2.6 on 2021-04-05 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_cryptocoins3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoins3',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
