# Generated by Django 2.2.6 on 2021-04-05 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cryptocoins3_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoins3',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=False, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
