# Generated by Django 2.2.6 on 2021-04-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210407_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
    ]
